### ISSUE TITLE
Custom favicon not working

### ISSUE THREAD

**Issue by aphe** [mmornati/ghost-cloudinary-store#4]
Just wanna move sethbrasile/ghost-cloudinary-store#18 to here.

i create the temporary patch,

please review it 

```js
  read(options) {
    options = options || {};
    return new BlueBird(function (resolve, reject) {
      var request = require('request').defaults({ encoding: null });
      request.get(options.path, function (err, res) {
        if (err) {
          reject(new Error("Cannot download image"))
        } else {
          resolve(res.body)
        }
      });
    });
  }
```

it is works for my case (install using ghost-cli).

**Comment by mmornati** [comment]
It seems good. What is the options variable which is pass to the read method? Cause you are then using option.path to access to the image. Is that the full path to the cloudinary url?

**Comment by mmornati** [comment]
@aphe you have now access as contributor to this repository. You can deliver what you want :) Then there is Travis which is building and releasing to npm the new library version (you have to update the version number intot he package.json file)

**Comment by mmornati** [comment]
Fixed: thanks to @aphe

**Comment by aphe** [comment]
@mmornati the options.path is ghost implementation that i got from [here](https://github.com/TryGhost/Ghost/blob/e8f85fd3dafd73fe670f0ed8ee7c63f6c389f9c5/core/server/adapters/storage/LocalFileStorage.js#L116), i guess ghost need to load the binary file.

**Comment by mmornati** [comment]
Ok good. Thanks for the information. I pushed your changes and tested locally and on my blog. All is working good. Great job man! Thanks!
I just need to implement some unit tests on this method to grow up the test coverage :P

**Comment by aphe** [comment]
can i  suggest something?

[this line](https://github.com/mmornati/ghost-cloudinary-store/blob/c13301426c61f68f576bd06998a1f3b64e2f1c5f/index.js#L30)

can i make it like this?

```js
    cloudinaryFileSettings.public_id = path.parse(this.getSanitizedFileName(image.name)).name;
```
so instead of `![myimage.png](https://res.cloudinary.com/../myimage.png.png)` it will return `![myimage](https://res.cloudinary.com/../myimage.png)`

**Comment by mmornati** [comment]
For sure you can. And yeah you are it is better.
You can normally deliver it directly on the repo. I added you as contributor so enjoy. It is better if you deliver your good ideas with your name :)
