### ISSUE TITLE
Build failing due to file renaming

### ISSUE THREAD

**Issue by mmornati** [mmornati/ghost-cloudinary-store#5]
After the last changing on file renaming build are failing due to unexpected values.
The Information about the build are here: https://travis-ci.org/mmornati/ghost-cloudinary-store/builds/279018186

**Comment by mmornati** [comment]
You are the best, man. To deliver it on npm we actually need to change the version in the package.json file. It is not so smart... I will try to think to a way to make it automatic with a tag. Anyway I will take care to this later...

**Comment by aphe** [comment]
ah yes, sorry i forget about that. And thank you
