### ISSUE TITLE
Blog throws 502 on activating this store

### ISSUE THREAD

**Issue by pankajpatel** [mmornati/ghost-cloudinary-store#8]
Hello,
I am not sure what I am doing wrong while enabling cloudinary store on my blog, whenever I enable the store and restart ghost, blog throws 502 errors.

My config looks like following:
```
  "storage": {
    "active": "ghost-cloudinary-store",
    "ghost-cloudinary-store": {
        "cloud_name": "....",
        "api_key": "....",
        "api_secret": "....",
        "configuration": {
            "image": {
                "quality": "auto:good",
                "secure": "true"
            },
            "file": {
                "use_filename": "true",
                "unique_filename": "false",
                "phash": "true",
                "overwrite": "false",
                "invalidate": "true"
            }
         }
    }
  }
```

I installed the store via npm and did following:
```
cp -r node_modules/ghost-cloudinary-store content/storage
```

Please help.

**Comment by mmornati** [comment]
Hello,
Do you have any other kind of error, in the log for example. It can help to find out the problem.
On my side I've a configuration like your one, the only different part is the one for the authentication: I'm not using the key and secret but an environment variable instead (CLOUDINARY_URL=cloudinary://874837483274837:a676b67565c6767a6767d6767f676fe1@sample) and all works with no problem.

If you find any other information about your error in the log don't hesitate to paste it here, I will try to help you as far as I can (sorry for the delay but I wasn't notify by github for this issue).

**Comment by pankajpatel** [comment]
Hey, thanks for responding.
I tried the environment variable as well, same 502 on blog.

I tried checking the error and access logs of nginx as well, bu it just say about error occurrence, no debug info. Do you know where I can check the error details?

**Comment by mmornati** [comment]
You have to check on your blog instance and not nginx. I don't know how you
run it, if it is via a docker is simple :).

And, anyway, in your ghost content folder you should be able to find a logs
folder.
Try to check there as starting point.

Marco

**Comment by aphe** [comment]
how do you install ghost @pankajpatel ?
try to check your current user home folder (~/.ghost)

**Comment by pankajpatel** [comment]
@aphe I installed ghost with ghost-cli

**Comment by pankajpatel** [comment]
The storage adapter didn't work with Env variable, but the configs in the config file.
Thanks.
